### ISSUE TITLE
Use all punctuation marks as distinctive features

### ISSUE THREAD

**Issue by palkeo** [jpotts18/stylometry#4]
Hi !

Your library is really interesting, thanks :)

I was wondering : Don't you think it would also be interesting to include other characteristics like the sequence of non-alphanumeric characters ?

For example, in this message I used « :) » which is a distinctive feature of my writing (I use it a lot). I'm also always putting a space before my question/exclamation marks (because I'm French).
Oh, I also like parenthesis (doesn't seems to be in your ponctuation analysis).

So, why not do a very generic punctuation analysis, for each non-alphanumeric character, or sequence of non-alphanumeric characters ?
That would be really powerful ! Like, you could detect someone that always do 2 carriage return after a sentence, to change paragraph (because the frequence of « .\n\n »).

For me, you could tell that I'm always using french quotes («) followed by an insecable space. That's really really distinctive (even if you can't see it ;))

**Comment by jpotts18** [comment]
Hey Palkeo ! Thanks for finding my software. It looks like you have some experience writing your own stylometry analyzer. I'd be totally fine with you adding this to the project.

**Comment by palkeo** [comment]
Hi !
I don't have time right now, so I made an issue in case someone wants to do it.
But I think I'll implement this when I will have the time and motivation, and send you a PR :)

**Comment by kimaniidaniel** [comment]
This is actually a VERY good predictor also. Was it ever worked on?

**Comment by palkeo** [comment]
No, I didn't do anything… (I tried to make my own analyzer a looong time ago but it was way more powerful than it, but yes, adding these features to the classifier would be great !).

If you want to work on it or anything, I'm curious to see what you do :)
